import SearchAppBar from './components/SearchAppBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <SearchAppBar />

        <main>
          {children}
        </main>
      </body>

    </html>
  )
}
